import pygame
from time import sleep
pygame.init()
window = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
pygame.mixer.init()
pygame.mixer.music.load('mother.mp3')
pygame.mixer.music.play()
image1 = pygame.image.load('img1.jpg')
window.blit(image1, (0, 0))
pygame.display.update()
sleep(5)
image3 = pygame.image.load('nobi1.jpg')
window.blit(image3, (0, 0))
pygame.display.update()
sleep(20)
image4 = pygame.image.load('shin1.png')
window.blit(image4, (0, 0))
pygame.display.update()
sleep(25)
image5 = pygame.image.load('shin2.jpg')
window.blit(image5, (0, 0))
pygame.display.update()
sleep(30)
image5 = pygame.image.load('ash1.jpg')
window.blit(image5, (0, 0))
pygame.display.update()
sleep(40)

